version: "3.5"

services:
  pulse:
    build: .
    container_name: pulse
    working_dir: /app
    env_file:
      - .development.env
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - iasodb_next_my_network
    restart: always

networks:
  iasodb_next_my_network:
    external: true